# For Java 8, try this
# FROM openjdk:8-jdk-alpine

# For Java 11, try this
FROM adoptopenjdk/openjdk11:alpine-jre

# Refer to Maven build -> finalName
ARG JAR_FILE=target/proposta.jar

# cd /opt/app
#WORKDIR /opt/app

# cp target/spring-boot-web.jar /opt/app/proposta.jar
#COPY ${JAR_FILE} propostas.jar

ADD ${JAR_FILE} propostas.jar

# EXPOSE 1111
# java -jar /opt/app/app.jar
ENTRYPOINT ["java","-Xmx512m","-jar","/propostas.jar"]