version: '3'
services:
  proposals-db:
    image: postgres:9.6
    volumes:
      - postgres-volume2:/var/lib/postgresql/data
      - ./scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=proposals_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - MAX_CONNECTIONS=300

volumes:
  postgres-volume2: